version: '2.0'
services:
    pws:
        # pwd daemon container always needs to be named this way
        container_name: pws
        # use the latest golang image
        image: personal-website
        # go to the right place and starts the app
        command: node_modules/.bin/http-server public -p 8080
        #volumes:
        ports:
            - "8080:8080"

    haproxy:
        container_name: haproxy
        image: haproxy
        ports:
        #    - "80:80"
            - "443:443"
        #volumes:
            
#volumes:
#    sessions:
#    networks:
